on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t "${GITHUB_REPOSITORY,,}" .
      - name: nose tests
        run: docker run -w /usr/local/src --entrypoint /bin/sh "${GITHUB_REPOSITORY,,}" -c 'pip install nose && nosetests'

  publish:
    runs-on: ubuntu-20.04
    needs: [test]
    if: github.event_name == 'push' || github.event_name == 'release'
    steps:
      - uses: fnndsc/chrisstore-build-and-publish@v1
        with:
          description: "A lung CT scan data pack."
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          chrisstore_token: ${{ secrets.CHRIS_STORE_USER }}
          readme-filepath: ./README.rst
